// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package cluster

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/eks"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/eks/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/eks-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Cluster{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.DescribeClusterOutput
	resp, err = rm.sdkapi.DescribeCluster(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "DescribeCluster", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.Cluster.AccessConfig != nil {
		f0 := &svcapitypes.CreateAccessConfigRequest{}
		if resp.Cluster.AccessConfig.AuthenticationMode != "" {
			f0.AuthenticationMode = aws.String(string(resp.Cluster.AccessConfig.AuthenticationMode))
		}
		if resp.Cluster.AccessConfig.BootstrapClusterCreatorAdminPermissions != nil {
			f0.BootstrapClusterCreatorAdminPermissions = resp.Cluster.AccessConfig.BootstrapClusterCreatorAdminPermissions
		}
		ko.Spec.AccessConfig = f0
	} else {
		ko.Spec.AccessConfig = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Cluster.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Cluster.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Cluster.CertificateAuthority != nil {
		f2 := &svcapitypes.Certificate{}
		if resp.Cluster.CertificateAuthority.Data != nil {
			f2.Data = resp.Cluster.CertificateAuthority.Data
		}
		ko.Status.CertificateAuthority = f2
	} else {
		ko.Status.CertificateAuthority = nil
	}
	if resp.Cluster.ClientRequestToken != nil {
		ko.Spec.ClientRequestToken = resp.Cluster.ClientRequestToken
	} else {
		ko.Spec.ClientRequestToken = nil
	}
	if resp.Cluster.ComputeConfig != nil {
		f4 := &svcapitypes.ComputeConfigRequest{}
		if resp.Cluster.ComputeConfig.Enabled != nil {
			f4.Enabled = resp.Cluster.ComputeConfig.Enabled
		}
		if resp.Cluster.ComputeConfig.NodePools != nil {
			f4.NodePools = aws.StringSlice(resp.Cluster.ComputeConfig.NodePools)
		}
		if resp.Cluster.ComputeConfig.NodeRoleArn != nil {
			f4.NodeRoleARN = resp.Cluster.ComputeConfig.NodeRoleArn
		}
		ko.Spec.ComputeConfig = f4
	} else {
		ko.Spec.ComputeConfig = nil
	}
	if resp.Cluster.ConnectorConfig != nil {
		f5 := &svcapitypes.ConnectorConfigResponse{}
		if resp.Cluster.ConnectorConfig.ActivationCode != nil {
			f5.ActivationCode = resp.Cluster.ConnectorConfig.ActivationCode
		}
		if resp.Cluster.ConnectorConfig.ActivationExpiry != nil {
			f5.ActivationExpiry = &metav1.Time{*resp.Cluster.ConnectorConfig.ActivationExpiry}
		}
		if resp.Cluster.ConnectorConfig.ActivationId != nil {
			f5.ActivationID = resp.Cluster.ConnectorConfig.ActivationId
		}
		if resp.Cluster.ConnectorConfig.Provider != nil {
			f5.Provider = resp.Cluster.ConnectorConfig.Provider
		}
		if resp.Cluster.ConnectorConfig.RoleArn != nil {
			f5.RoleARN = resp.Cluster.ConnectorConfig.RoleArn
		}
		ko.Status.ConnectorConfig = f5
	} else {
		ko.Status.ConnectorConfig = nil
	}
	if resp.Cluster.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.Cluster.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Cluster.DeletionProtection != nil {
		ko.Spec.DeletionProtection = resp.Cluster.DeletionProtection
	} else {
		ko.Spec.DeletionProtection = nil
	}
	if resp.Cluster.EncryptionConfig != nil {
		f8 := []*svcapitypes.EncryptionConfig{}
		for _, f8iter := range resp.Cluster.EncryptionConfig {
			f8elem := &svcapitypes.EncryptionConfig{}
			if f8iter.Provider != nil {
				f8elemf0 := &svcapitypes.Provider{}
				if f8iter.Provider.KeyArn != nil {
					f8elemf0.KeyARN = f8iter.Provider.KeyArn
				}
				f8elem.Provider = f8elemf0
			}
			if f8iter.Resources != nil {
				f8elem.Resources = aws.StringSlice(f8iter.Resources)
			}
			f8 = append(f8, f8elem)
		}
		ko.Spec.EncryptionConfig = f8
	} else {
		ko.Spec.EncryptionConfig = nil
	}
	if resp.Cluster.Endpoint != nil {
		ko.Status.Endpoint = resp.Cluster.Endpoint
	} else {
		ko.Status.Endpoint = nil
	}
	if resp.Cluster.Health != nil {
		f10 := &svcapitypes.ClusterHealth{}
		if resp.Cluster.Health.Issues != nil {
			f10f0 := []*svcapitypes.ClusterIssue{}
			for _, f10f0iter := range resp.Cluster.Health.Issues {
				f10f0elem := &svcapitypes.ClusterIssue{}
				if f10f0iter.Code != "" {
					f10f0elem.Code = aws.String(string(f10f0iter.Code))
				}
				if f10f0iter.Message != nil {
					f10f0elem.Message = f10f0iter.Message
				}
				if f10f0iter.ResourceIds != nil {
					f10f0elem.ResourceIDs = aws.StringSlice(f10f0iter.ResourceIds)
				}
				f10f0 = append(f10f0, f10f0elem)
			}
			f10.Issues = f10f0
		}
		ko.Status.Health = f10
	} else {
		ko.Status.Health = nil
	}
	if resp.Cluster.Id != nil {
		ko.Status.ID = resp.Cluster.Id
	} else {
		ko.Status.ID = nil
	}
	if resp.Cluster.Identity != nil {
		f12 := &svcapitypes.Identity{}
		if resp.Cluster.Identity.Oidc != nil {
			f12f0 := &svcapitypes.OIDC{}
			if resp.Cluster.Identity.Oidc.Issuer != nil {
				f12f0.Issuer = resp.Cluster.Identity.Oidc.Issuer
			}
			f12.OIDC = f12f0
		}
		ko.Status.Identity = f12
	} else {
		ko.Status.Identity = nil
	}
	if resp.Cluster.KubernetesNetworkConfig != nil {
		f13 := &svcapitypes.KubernetesNetworkConfigRequest{}
		if resp.Cluster.KubernetesNetworkConfig.ElasticLoadBalancing != nil {
			f13f0 := &svcapitypes.ElasticLoadBalancing{}
			if resp.Cluster.KubernetesNetworkConfig.ElasticLoadBalancing.Enabled != nil {
				f13f0.Enabled = resp.Cluster.KubernetesNetworkConfig.ElasticLoadBalancing.Enabled
			}
			f13.ElasticLoadBalancing = f13f0
		}
		if resp.Cluster.KubernetesNetworkConfig.IpFamily != "" {
			f13.IPFamily = aws.String(string(resp.Cluster.KubernetesNetworkConfig.IpFamily))
		}
		if resp.Cluster.KubernetesNetworkConfig.ServiceIpv4Cidr != nil {
			f13.ServiceIPv4CIDR = resp.Cluster.KubernetesNetworkConfig.ServiceIpv4Cidr
		}
		ko.Spec.KubernetesNetworkConfig = f13
	} else {
		ko.Spec.KubernetesNetworkConfig = nil
	}
	if resp.Cluster.Logging != nil {
		f14 := &svcapitypes.Logging{}
		if resp.Cluster.Logging.ClusterLogging != nil {
			f14f0 := []*svcapitypes.LogSetup{}
			for _, f14f0iter := range resp.Cluster.Logging.ClusterLogging {
				f14f0elem := &svcapitypes.LogSetup{}
				if f14f0iter.Enabled != nil {
					f14f0elem.Enabled = f14f0iter.Enabled
				}
				if f14f0iter.Types != nil {
					f14f0elemf1 := []*string{}
					for _, f14f0elemf1iter := range f14f0iter.Types {
						var f14f0elemf1elem *string
						f14f0elemf1elem = aws.String(string(f14f0elemf1iter))
						f14f0elemf1 = append(f14f0elemf1, f14f0elemf1elem)
					}
					f14f0elem.Types = f14f0elemf1
				}
				f14f0 = append(f14f0, f14f0elem)
			}
			f14.ClusterLogging = f14f0
		}
		ko.Spec.Logging = f14
	} else {
		ko.Spec.Logging = nil
	}
	if resp.Cluster.Name != nil {
		ko.Spec.Name = resp.Cluster.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.Cluster.OutpostConfig != nil {
		f16 := &svcapitypes.OutpostConfigRequest{}
		if resp.Cluster.OutpostConfig.ControlPlaneInstanceType != nil {
			f16.ControlPlaneInstanceType = resp.Cluster.OutpostConfig.ControlPlaneInstanceType
		}
		if resp.Cluster.OutpostConfig.ControlPlanePlacement != nil {
			f16f1 := &svcapitypes.ControlPlanePlacementRequest{}
			if resp.Cluster.OutpostConfig.ControlPlanePlacement.GroupName != nil {
				f16f1.GroupName = resp.Cluster.OutpostConfig.ControlPlanePlacement.GroupName
			}
			f16.ControlPlanePlacement = f16f1
		}
		if resp.Cluster.OutpostConfig.OutpostArns != nil {
			f16.OutpostARNs = aws.StringSlice(resp.Cluster.OutpostConfig.OutpostArns)
		}
		ko.Spec.OutpostConfig = f16
	} else {
		ko.Spec.OutpostConfig = nil
	}
	if resp.Cluster.PlatformVersion != nil {
		ko.Status.PlatformVersion = resp.Cluster.PlatformVersion
	} else {
		ko.Status.PlatformVersion = nil
	}
	if resp.Cluster.RemoteNetworkConfig != nil {
		f18 := &svcapitypes.RemoteNetworkConfigRequest{}
		if resp.Cluster.RemoteNetworkConfig.RemoteNodeNetworks != nil {
			f18f0 := []*svcapitypes.RemoteNodeNetwork{}
			for _, f18f0iter := range resp.Cluster.RemoteNetworkConfig.RemoteNodeNetworks {
				f18f0elem := &svcapitypes.RemoteNodeNetwork{}
				if f18f0iter.Cidrs != nil {
					f18f0elem.CIDRs = aws.StringSlice(f18f0iter.Cidrs)
				}
				f18f0 = append(f18f0, f18f0elem)
			}
			f18.RemoteNodeNetworks = f18f0
		}
		if resp.Cluster.RemoteNetworkConfig.RemotePodNetworks != nil {
			f18f1 := []*svcapitypes.RemotePodNetwork{}
			for _, f18f1iter := range resp.Cluster.RemoteNetworkConfig.RemotePodNetworks {
				f18f1elem := &svcapitypes.RemotePodNetwork{}
				if f18f1iter.Cidrs != nil {
					f18f1elem.CIDRs = aws.StringSlice(f18f1iter.Cidrs)
				}
				f18f1 = append(f18f1, f18f1elem)
			}
			f18.RemotePodNetworks = f18f1
		}
		ko.Spec.RemoteNetworkConfig = f18
	} else {
		ko.Spec.RemoteNetworkConfig = nil
	}
	if resp.Cluster.ResourcesVpcConfig != nil {
		f19 := &svcapitypes.VPCConfigRequest{}
		f19.EndpointPrivateAccess = &resp.Cluster.ResourcesVpcConfig.EndpointPrivateAccess
		f19.EndpointPublicAccess = &resp.Cluster.ResourcesVpcConfig.EndpointPublicAccess
		if resp.Cluster.ResourcesVpcConfig.PublicAccessCidrs != nil {
			f19.PublicAccessCIDRs = aws.StringSlice(resp.Cluster.ResourcesVpcConfig.PublicAccessCidrs)
		}
		if resp.Cluster.ResourcesVpcConfig.SecurityGroupIds != nil {
			f19.SecurityGroupIDs = aws.StringSlice(resp.Cluster.ResourcesVpcConfig.SecurityGroupIds)
		}
		if resp.Cluster.ResourcesVpcConfig.SubnetIds != nil {
			f19.SubnetIDs = aws.StringSlice(resp.Cluster.ResourcesVpcConfig.SubnetIds)
		}
		ko.Spec.ResourcesVPCConfig = f19
	} else {
		ko.Spec.ResourcesVPCConfig = nil
	}
	if resp.Cluster.RoleArn != nil {
		ko.Spec.RoleARN = resp.Cluster.RoleArn
	} else {
		ko.Spec.RoleARN = nil
	}
	if resp.Cluster.Status != "" {
		ko.Status.Status = aws.String(string(resp.Cluster.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.Cluster.StorageConfig != nil {
		f22 := &svcapitypes.StorageConfigRequest{}
		if resp.Cluster.StorageConfig.BlockStorage != nil {
			f22f0 := &svcapitypes.BlockStorage{}
			if resp.Cluster.StorageConfig.BlockStorage.Enabled != nil {
				f22f0.Enabled = resp.Cluster.StorageConfig.BlockStorage.Enabled
			}
			f22.BlockStorage = f22f0
		}
		ko.Spec.StorageConfig = f22
	} else {
		ko.Spec.StorageConfig = nil
	}
	if resp.Cluster.Tags != nil {
		ko.Spec.Tags = aws.StringMap(resp.Cluster.Tags)
	} else {
		ko.Spec.Tags = nil
	}
	if resp.Cluster.UpgradePolicy != nil {
		f24 := &svcapitypes.UpgradePolicyRequest{}
		if resp.Cluster.UpgradePolicy.SupportType != "" {
			f24.SupportType = aws.String(string(resp.Cluster.UpgradePolicy.SupportType))
		}
		ko.Spec.UpgradePolicy = f24
	} else {
		ko.Spec.UpgradePolicy = nil
	}
	if resp.Cluster.Version != nil {
		ko.Spec.Version = resp.Cluster.Version
	} else {
		ko.Spec.Version = nil
	}
	if resp.Cluster.ZonalShiftConfig != nil {
		f26 := &svcapitypes.ZonalShiftConfigRequest{}
		if resp.Cluster.ZonalShiftConfig.Enabled != nil {
			f26.Enabled = resp.Cluster.ZonalShiftConfig.Enabled
		}
		ko.Spec.ZonalShiftConfig = f26
	} else {
		ko.Spec.ZonalShiftConfig = nil
	}

	rm.setStatusDefaults(ko)
	if resp.Cluster.ResourcesVpcConfig != nil && resp.Cluster.ResourcesVpcConfig.ClusterSecurityGroupId != nil {
		ko.Status.ClusterSecurityGroupID = resp.Cluster.ResourcesVpcConfig.ClusterSecurityGroupId
	}

	if r.ko.Spec.ResourcesVPCConfig != nil && r.ko.Spec.ResourcesVPCConfig.SubnetRefs != nil {
		ko.Spec.ResourcesVPCConfig.SubnetRefs = r.ko.Spec.ResourcesVPCConfig.SubnetRefs
	}

	if r.ko.Spec.ResourcesVPCConfig != nil && r.ko.Spec.ResourcesVPCConfig.SecurityGroupRefs != nil {
		ko.Spec.ResourcesVPCConfig.SecurityGroupRefs = r.ko.Spec.ResourcesVPCConfig.SecurityGroupRefs
	}

	if !clusterActive(&resource{ko}) {
		// Setting resource synced condition to false will trigger a requeue of
		// the resource. No need to return a requeue error here.
		ackcondition.SetSynced(&resource{ko}, corev1.ConditionFalse, nil, nil)
	} else {
		ackcondition.SetSynced(&resource{ko}, corev1.ConditionTrue, nil, nil)
	}
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.Name == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.DescribeClusterInput, error) {
	res := &svcsdk.DescribeClusterInput{}

	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateClusterOutput
	_ = resp
	resp, err = rm.sdkapi.CreateCluster(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateCluster", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.Cluster.AccessConfig != nil {
		f0 := &svcapitypes.CreateAccessConfigRequest{}
		if resp.Cluster.AccessConfig.AuthenticationMode != "" {
			f0.AuthenticationMode = aws.String(string(resp.Cluster.AccessConfig.AuthenticationMode))
		}
		if resp.Cluster.AccessConfig.BootstrapClusterCreatorAdminPermissions != nil {
			f0.BootstrapClusterCreatorAdminPermissions = resp.Cluster.AccessConfig.BootstrapClusterCreatorAdminPermissions
		}
		ko.Spec.AccessConfig = f0
	} else {
		ko.Spec.AccessConfig = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Cluster.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Cluster.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Cluster.CertificateAuthority != nil {
		f2 := &svcapitypes.Certificate{}
		if resp.Cluster.CertificateAuthority.Data != nil {
			f2.Data = resp.Cluster.CertificateAuthority.Data
		}
		ko.Status.CertificateAuthority = f2
	} else {
		ko.Status.CertificateAuthority = nil
	}
	if resp.Cluster.ClientRequestToken != nil {
		ko.Spec.ClientRequestToken = resp.Cluster.ClientRequestToken
	} else {
		ko.Spec.ClientRequestToken = nil
	}
	if resp.Cluster.ComputeConfig != nil {
		f4 := &svcapitypes.ComputeConfigRequest{}
		if resp.Cluster.ComputeConfig.Enabled != nil {
			f4.Enabled = resp.Cluster.ComputeConfig.Enabled
		}
		if resp.Cluster.ComputeConfig.NodePools != nil {
			f4.NodePools = aws.StringSlice(resp.Cluster.ComputeConfig.NodePools)
		}
		if resp.Cluster.ComputeConfig.NodeRoleArn != nil {
			f4.NodeRoleARN = resp.Cluster.ComputeConfig.NodeRoleArn
		}
		ko.Spec.ComputeConfig = f4
	} else {
		ko.Spec.ComputeConfig = nil
	}
	if resp.Cluster.ConnectorConfig != nil {
		f5 := &svcapitypes.ConnectorConfigResponse{}
		if resp.Cluster.ConnectorConfig.ActivationCode != nil {
			f5.ActivationCode = resp.Cluster.ConnectorConfig.ActivationCode
		}
		if resp.Cluster.ConnectorConfig.ActivationExpiry != nil {
			f5.ActivationExpiry = &metav1.Time{*resp.Cluster.ConnectorConfig.ActivationExpiry}
		}
		if resp.Cluster.ConnectorConfig.ActivationId != nil {
			f5.ActivationID = resp.Cluster.ConnectorConfig.ActivationId
		}
		if resp.Cluster.ConnectorConfig.Provider != nil {
			f5.Provider = resp.Cluster.ConnectorConfig.Provider
		}
		if resp.Cluster.ConnectorConfig.RoleArn != nil {
			f5.RoleARN = resp.Cluster.ConnectorConfig.RoleArn
		}
		ko.Status.ConnectorConfig = f5
	} else {
		ko.Status.ConnectorConfig = nil
	}
	if resp.Cluster.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.Cluster.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Cluster.DeletionProtection != nil {
		ko.Spec.DeletionProtection = resp.Cluster.DeletionProtection
	} else {
		ko.Spec.DeletionProtection = nil
	}
	if resp.Cluster.EncryptionConfig != nil {
		f8 := []*svcapitypes.EncryptionConfig{}
		for _, f8iter := range resp.Cluster.EncryptionConfig {
			f8elem := &svcapitypes.EncryptionConfig{}
			if f8iter.Provider != nil {
				f8elemf0 := &svcapitypes.Provider{}
				if f8iter.Provider.KeyArn != nil {
					f8elemf0.KeyARN = f8iter.Provider.KeyArn
				}
				f8elem.Provider = f8elemf0
			}
			if f8iter.Resources != nil {
				f8elem.Resources = aws.StringSlice(f8iter.Resources)
			}
			f8 = append(f8, f8elem)
		}
		ko.Spec.EncryptionConfig = f8
	} else {
		ko.Spec.EncryptionConfig = nil
	}
	if resp.Cluster.Endpoint != nil {
		ko.Status.Endpoint = resp.Cluster.Endpoint
	} else {
		ko.Status.Endpoint = nil
	}
	if resp.Cluster.Health != nil {
		f10 := &svcapitypes.ClusterHealth{}
		if resp.Cluster.Health.Issues != nil {
			f10f0 := []*svcapitypes.ClusterIssue{}
			for _, f10f0iter := range resp.Cluster.Health.Issues {
				f10f0elem := &svcapitypes.ClusterIssue{}
				if f10f0iter.Code != "" {
					f10f0elem.Code = aws.String(string(f10f0iter.Code))
				}
				if f10f0iter.Message != nil {
					f10f0elem.Message = f10f0iter.Message
				}
				if f10f0iter.ResourceIds != nil {
					f10f0elem.ResourceIDs = aws.StringSlice(f10f0iter.ResourceIds)
				}
				f10f0 = append(f10f0, f10f0elem)
			}
			f10.Issues = f10f0
		}
		ko.Status.Health = f10
	} else {
		ko.Status.Health = nil
	}
	if resp.Cluster.Id != nil {
		ko.Status.ID = resp.Cluster.Id
	} else {
		ko.Status.ID = nil
	}
	if resp.Cluster.Identity != nil {
		f12 := &svcapitypes.Identity{}
		if resp.Cluster.Identity.Oidc != nil {
			f12f0 := &svcapitypes.OIDC{}
			if resp.Cluster.Identity.Oidc.Issuer != nil {
				f12f0.Issuer = resp.Cluster.Identity.Oidc.Issuer
			}
			f12.OIDC = f12f0
		}
		ko.Status.Identity = f12
	} else {
		ko.Status.Identity = nil
	}
	if resp.Cluster.KubernetesNetworkConfig != nil {
		f13 := &svcapitypes.KubernetesNetworkConfigRequest{}
		if resp.Cluster.KubernetesNetworkConfig.ElasticLoadBalancing != nil {
			f13f0 := &svcapitypes.ElasticLoadBalancing{}
			if resp.Cluster.KubernetesNetworkConfig.ElasticLoadBalancing.Enabled != nil {
				f13f0.Enabled = resp.Cluster.KubernetesNetworkConfig.ElasticLoadBalancing.Enabled
			}
			f13.ElasticLoadBalancing = f13f0
		}
		if resp.Cluster.KubernetesNetworkConfig.IpFamily != "" {
			f13.IPFamily = aws.String(string(resp.Cluster.KubernetesNetworkConfig.IpFamily))
		}
		if resp.Cluster.KubernetesNetworkConfig.ServiceIpv4Cidr != nil {
			f13.ServiceIPv4CIDR = resp.Cluster.KubernetesNetworkConfig.ServiceIpv4Cidr
		}
		ko.Spec.KubernetesNetworkConfig = f13
	} else {
		ko.Spec.KubernetesNetworkConfig = nil
	}
	if resp.Cluster.Logging != nil {
		f14 := &svcapitypes.Logging{}
		if resp.Cluster.Logging.ClusterLogging != nil {
			f14f0 := []*svcapitypes.LogSetup{}
			for _, f14f0iter := range resp.Cluster.Logging.ClusterLogging {
				f14f0elem := &svcapitypes.LogSetup{}
				if f14f0iter.Enabled != nil {
					f14f0elem.Enabled = f14f0iter.Enabled
				}
				if f14f0iter.Types != nil {
					f14f0elemf1 := []*string{}
					for _, f14f0elemf1iter := range f14f0iter.Types {
						var f14f0elemf1elem *string
						f14f0elemf1elem = aws.String(string(f14f0elemf1iter))
						f14f0elemf1 = append(f14f0elemf1, f14f0elemf1elem)
					}
					f14f0elem.Types = f14f0elemf1
				}
				f14f0 = append(f14f0, f14f0elem)
			}
			f14.ClusterLogging = f14f0
		}
		ko.Spec.Logging = f14
	} else {
		ko.Spec.Logging = nil
	}
	if resp.Cluster.Name != nil {
		ko.Spec.Name = resp.Cluster.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.Cluster.OutpostConfig != nil {
		f16 := &svcapitypes.OutpostConfigRequest{}
		if resp.Cluster.OutpostConfig.ControlPlaneInstanceType != nil {
			f16.ControlPlaneInstanceType = resp.Cluster.OutpostConfig.ControlPlaneInstanceType
		}
		if resp.Cluster.OutpostConfig.ControlPlanePlacement != nil {
			f16f1 := &svcapitypes.ControlPlanePlacementRequest{}
			if resp.Cluster.OutpostConfig.ControlPlanePlacement.GroupName != nil {
				f16f1.GroupName = resp.Cluster.OutpostConfig.ControlPlanePlacement.GroupName
			}
			f16.ControlPlanePlacement = f16f1
		}
		if resp.Cluster.OutpostConfig.OutpostArns != nil {
			f16.OutpostARNs = aws.StringSlice(resp.Cluster.OutpostConfig.OutpostArns)
		}
		ko.Spec.OutpostConfig = f16
	} else {
		ko.Spec.OutpostConfig = nil
	}
	if resp.Cluster.PlatformVersion != nil {
		ko.Status.PlatformVersion = resp.Cluster.PlatformVersion
	} else {
		ko.Status.PlatformVersion = nil
	}
	if resp.Cluster.RemoteNetworkConfig != nil {
		f18 := &svcapitypes.RemoteNetworkConfigRequest{}
		if resp.Cluster.RemoteNetworkConfig.RemoteNodeNetworks != nil {
			f18f0 := []*svcapitypes.RemoteNodeNetwork{}
			for _, f18f0iter := range resp.Cluster.RemoteNetworkConfig.RemoteNodeNetworks {
				f18f0elem := &svcapitypes.RemoteNodeNetwork{}
				if f18f0iter.Cidrs != nil {
					f18f0elem.CIDRs = aws.StringSlice(f18f0iter.Cidrs)
				}
				f18f0 = append(f18f0, f18f0elem)
			}
			f18.RemoteNodeNetworks = f18f0
		}
		if resp.Cluster.RemoteNetworkConfig.RemotePodNetworks != nil {
			f18f1 := []*svcapitypes.RemotePodNetwork{}
			for _, f18f1iter := range resp.Cluster.RemoteNetworkConfig.RemotePodNetworks {
				f18f1elem := &svcapitypes.RemotePodNetwork{}
				if f18f1iter.Cidrs != nil {
					f18f1elem.CIDRs = aws.StringSlice(f18f1iter.Cidrs)
				}
				f18f1 = append(f18f1, f18f1elem)
			}
			f18.RemotePodNetworks = f18f1
		}
		ko.Spec.RemoteNetworkConfig = f18
	} else {
		ko.Spec.RemoteNetworkConfig = nil
	}
	if resp.Cluster.ResourcesVpcConfig != nil {
		f19 := &svcapitypes.VPCConfigRequest{}
		f19.EndpointPrivateAccess = &resp.Cluster.ResourcesVpcConfig.EndpointPrivateAccess
		f19.EndpointPublicAccess = &resp.Cluster.ResourcesVpcConfig.EndpointPublicAccess
		if resp.Cluster.ResourcesVpcConfig.PublicAccessCidrs != nil {
			f19.PublicAccessCIDRs = aws.StringSlice(resp.Cluster.ResourcesVpcConfig.PublicAccessCidrs)
		}
		if resp.Cluster.ResourcesVpcConfig.SecurityGroupIds != nil {
			f19.SecurityGroupIDs = aws.StringSlice(resp.Cluster.ResourcesVpcConfig.SecurityGroupIds)
		}
		if resp.Cluster.ResourcesVpcConfig.SubnetIds != nil {
			f19.SubnetIDs = aws.StringSlice(resp.Cluster.ResourcesVpcConfig.SubnetIds)
		}
		ko.Spec.ResourcesVPCConfig = f19
	} else {
		ko.Spec.ResourcesVPCConfig = nil
	}
	if resp.Cluster.RoleArn != nil {
		ko.Spec.RoleARN = resp.Cluster.RoleArn
	} else {
		ko.Spec.RoleARN = nil
	}
	if resp.Cluster.Status != "" {
		ko.Status.Status = aws.String(string(resp.Cluster.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.Cluster.StorageConfig != nil {
		f22 := &svcapitypes.StorageConfigRequest{}
		if resp.Cluster.StorageConfig.BlockStorage != nil {
			f22f0 := &svcapitypes.BlockStorage{}
			if resp.Cluster.StorageConfig.BlockStorage.Enabled != nil {
				f22f0.Enabled = resp.Cluster.StorageConfig.BlockStorage.Enabled
			}
			f22.BlockStorage = f22f0
		}
		ko.Spec.StorageConfig = f22
	} else {
		ko.Spec.StorageConfig = nil
	}
	if resp.Cluster.Tags != nil {
		ko.Spec.Tags = aws.StringMap(resp.Cluster.Tags)
	} else {
		ko.Spec.Tags = nil
	}
	if resp.Cluster.UpgradePolicy != nil {
		f24 := &svcapitypes.UpgradePolicyRequest{}
		if resp.Cluster.UpgradePolicy.SupportType != "" {
			f24.SupportType = aws.String(string(resp.Cluster.UpgradePolicy.SupportType))
		}
		ko.Spec.UpgradePolicy = f24
	} else {
		ko.Spec.UpgradePolicy = nil
	}
	if resp.Cluster.Version != nil {
		ko.Spec.Version = resp.Cluster.Version
	} else {
		ko.Spec.Version = nil
	}
	if resp.Cluster.ZonalShiftConfig != nil {
		f26 := &svcapitypes.ZonalShiftConfigRequest{}
		if resp.Cluster.ZonalShiftConfig.Enabled != nil {
			f26.Enabled = resp.Cluster.ZonalShiftConfig.Enabled
		}
		ko.Spec.ZonalShiftConfig = f26
	} else {
		ko.Spec.ZonalShiftConfig = nil
	}

	rm.setStatusDefaults(ko)
	if resp.Cluster.ResourcesVpcConfig != nil && resp.Cluster.ResourcesVpcConfig.ClusterSecurityGroupId != nil {
		ko.Status.ClusterSecurityGroupID = resp.Cluster.ResourcesVpcConfig.ClusterSecurityGroupId
	}

	if desired.ko.Spec.ResourcesVPCConfig.SubnetRefs != nil {
		ko.Spec.ResourcesVPCConfig.SubnetRefs = desired.ko.Spec.ResourcesVPCConfig.SubnetRefs
	}

	if desired.ko.Spec.ResourcesVPCConfig.SecurityGroupRefs != nil {
		ko.Spec.ResourcesVPCConfig.SecurityGroupRefs = desired.ko.Spec.ResourcesVPCConfig.SecurityGroupRefs
	}

	// We expect the cluster to be in 'CREATING' status since we just issued
	// the call to create it, but I suppose it doesn't hurt to check here.
	if clusterCreating(&resource{ko}) {
		// Setting resource synced condition to false will trigger a requeue of
		// the resource. No need to return a requeue error here.
		ackcondition.SetSynced(&resource{ko}, corev1.ConditionFalse, nil, nil)
		return &resource{ko}, nil
	}

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateClusterInput, error) {
	res := &svcsdk.CreateClusterInput{}

	if r.ko.Spec.AccessConfig != nil {
		f0 := &svcsdktypes.CreateAccessConfigRequest{}
		if r.ko.Spec.AccessConfig.AuthenticationMode != nil {
			f0.AuthenticationMode = svcsdktypes.AuthenticationMode(*r.ko.Spec.AccessConfig.AuthenticationMode)
		}
		if r.ko.Spec.AccessConfig.BootstrapClusterCreatorAdminPermissions != nil {
			f0.BootstrapClusterCreatorAdminPermissions = r.ko.Spec.AccessConfig.BootstrapClusterCreatorAdminPermissions
		}
		res.AccessConfig = f0
	}
	if r.ko.Spec.BootstrapSelfManagedAddons != nil {
		res.BootstrapSelfManagedAddons = r.ko.Spec.BootstrapSelfManagedAddons
	}
	if r.ko.Spec.ClientRequestToken != nil {
		res.ClientRequestToken = r.ko.Spec.ClientRequestToken
	}
	if r.ko.Spec.ComputeConfig != nil {
		f3 := &svcsdktypes.ComputeConfigRequest{}
		if r.ko.Spec.ComputeConfig.Enabled != nil {
			f3.Enabled = r.ko.Spec.ComputeConfig.Enabled
		}
		if r.ko.Spec.ComputeConfig.NodePools != nil {
			f3.NodePools = aws.ToStringSlice(r.ko.Spec.ComputeConfig.NodePools)
		}
		if r.ko.Spec.ComputeConfig.NodeRoleARN != nil {
			f3.NodeRoleArn = r.ko.Spec.ComputeConfig.NodeRoleARN
		}
		res.ComputeConfig = f3
	}
	if r.ko.Spec.DeletionProtection != nil {
		res.DeletionProtection = r.ko.Spec.DeletionProtection
	}
	if r.ko.Spec.EncryptionConfig != nil {
		f5 := []svcsdktypes.EncryptionConfig{}
		for _, f5iter := range r.ko.Spec.EncryptionConfig {
			f5elem := &svcsdktypes.EncryptionConfig{}
			if f5iter.Provider != nil {
				f5elemf0 := &svcsdktypes.Provider{}
				if f5iter.Provider.KeyARN != nil {
					f5elemf0.KeyArn = f5iter.Provider.KeyARN
				}
				f5elem.Provider = f5elemf0
			}
			if f5iter.Resources != nil {
				f5elem.Resources = aws.ToStringSlice(f5iter.Resources)
			}
			f5 = append(f5, *f5elem)
		}
		res.EncryptionConfig = f5
	}
	if r.ko.Spec.KubernetesNetworkConfig != nil {
		f6 := &svcsdktypes.KubernetesNetworkConfigRequest{}
		if r.ko.Spec.KubernetesNetworkConfig.ElasticLoadBalancing != nil {
			f6f0 := &svcsdktypes.ElasticLoadBalancing{}
			if r.ko.Spec.KubernetesNetworkConfig.ElasticLoadBalancing.Enabled != nil {
				f6f0.Enabled = r.ko.Spec.KubernetesNetworkConfig.ElasticLoadBalancing.Enabled
			}
			f6.ElasticLoadBalancing = f6f0
		}
		if r.ko.Spec.KubernetesNetworkConfig.IPFamily != nil {
			f6.IpFamily = svcsdktypes.IpFamily(*r.ko.Spec.KubernetesNetworkConfig.IPFamily)
		}
		if r.ko.Spec.KubernetesNetworkConfig.ServiceIPv4CIDR != nil {
			f6.ServiceIpv4Cidr = r.ko.Spec.KubernetesNetworkConfig.ServiceIPv4CIDR
		}
		res.KubernetesNetworkConfig = f6
	}
	if r.ko.Spec.Logging != nil {
		f7 := &svcsdktypes.Logging{}
		if r.ko.Spec.Logging.ClusterLogging != nil {
			f7f0 := []svcsdktypes.LogSetup{}
			for _, f7f0iter := range r.ko.Spec.Logging.ClusterLogging {
				f7f0elem := &svcsdktypes.LogSetup{}
				if f7f0iter.Enabled != nil {
					f7f0elem.Enabled = f7f0iter.Enabled
				}
				if f7f0iter.Types != nil {
					f7f0elemf1 := []svcsdktypes.LogType{}
					for _, f7f0elemf1iter := range f7f0iter.Types {
						var f7f0elemf1elem string
						f7f0elemf1elem = string(*f7f0elemf1iter)
						f7f0elemf1 = append(f7f0elemf1, svcsdktypes.LogType(f7f0elemf1elem))
					}
					f7f0elem.Types = f7f0elemf1
				}
				f7f0 = append(f7f0, *f7f0elem)
			}
			f7.ClusterLogging = f7f0
		}
		res.Logging = f7
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.OutpostConfig != nil {
		f9 := &svcsdktypes.OutpostConfigRequest{}
		if r.ko.Spec.OutpostConfig.ControlPlaneInstanceType != nil {
			f9.ControlPlaneInstanceType = r.ko.Spec.OutpostConfig.ControlPlaneInstanceType
		}
		if r.ko.Spec.OutpostConfig.ControlPlanePlacement != nil {
			f9f1 := &svcsdktypes.ControlPlanePlacementRequest{}
			if r.ko.Spec.OutpostConfig.ControlPlanePlacement.GroupName != nil {
				f9f1.GroupName = r.ko.Spec.OutpostConfig.ControlPlanePlacement.GroupName
			}
			f9.ControlPlanePlacement = f9f1
		}
		if r.ko.Spec.OutpostConfig.OutpostARNs != nil {
			f9.OutpostArns = aws.ToStringSlice(r.ko.Spec.OutpostConfig.OutpostARNs)
		}
		res.OutpostConfig = f9
	}
	if r.ko.Spec.RemoteNetworkConfig != nil {
		f10 := &svcsdktypes.RemoteNetworkConfigRequest{}
		if r.ko.Spec.RemoteNetworkConfig.RemoteNodeNetworks != nil {
			f10f0 := []svcsdktypes.RemoteNodeNetwork{}
			for _, f10f0iter := range r.ko.Spec.RemoteNetworkConfig.RemoteNodeNetworks {
				f10f0elem := &svcsdktypes.RemoteNodeNetwork{}
				if f10f0iter.CIDRs != nil {
					f10f0elem.Cidrs = aws.ToStringSlice(f10f0iter.CIDRs)
				}
				f10f0 = append(f10f0, *f10f0elem)
			}
			f10.RemoteNodeNetworks = f10f0
		}
		if r.ko.Spec.RemoteNetworkConfig.RemotePodNetworks != nil {
			f10f1 := []svcsdktypes.RemotePodNetwork{}
			for _, f10f1iter := range r.ko.Spec.RemoteNetworkConfig.RemotePodNetworks {
				f10f1elem := &svcsdktypes.RemotePodNetwork{}
				if f10f1iter.CIDRs != nil {
					f10f1elem.Cidrs = aws.ToStringSlice(f10f1iter.CIDRs)
				}
				f10f1 = append(f10f1, *f10f1elem)
			}
			f10.RemotePodNetworks = f10f1
		}
		res.RemoteNetworkConfig = f10
	}
	if r.ko.Spec.ResourcesVPCConfig != nil {
		f11 := &svcsdktypes.VpcConfigRequest{}
		if r.ko.Spec.ResourcesVPCConfig.EndpointPrivateAccess != nil {
			f11.EndpointPrivateAccess = r.ko.Spec.ResourcesVPCConfig.EndpointPrivateAccess
		}
		if r.ko.Spec.ResourcesVPCConfig.EndpointPublicAccess != nil {
			f11.EndpointPublicAccess = r.ko.Spec.ResourcesVPCConfig.EndpointPublicAccess
		}
		if r.ko.Spec.ResourcesVPCConfig.PublicAccessCIDRs != nil {
			f11.PublicAccessCidrs = aws.ToStringSlice(r.ko.Spec.ResourcesVPCConfig.PublicAccessCIDRs)
		}
		if r.ko.Spec.ResourcesVPCConfig.SecurityGroupIDs != nil {
			f11.SecurityGroupIds = aws.ToStringSlice(r.ko.Spec.ResourcesVPCConfig.SecurityGroupIDs)
		}
		if r.ko.Spec.ResourcesVPCConfig.SubnetIDs != nil {
			f11.SubnetIds = aws.ToStringSlice(r.ko.Spec.ResourcesVPCConfig.SubnetIDs)
		}
		res.ResourcesVpcConfig = f11
	}
	if r.ko.Spec.RoleARN != nil {
		res.RoleArn = r.ko.Spec.RoleARN
	}
	if r.ko.Spec.StorageConfig != nil {
		f13 := &svcsdktypes.StorageConfigRequest{}
		if r.ko.Spec.StorageConfig.BlockStorage != nil {
			f13f0 := &svcsdktypes.BlockStorage{}
			if r.ko.Spec.StorageConfig.BlockStorage.Enabled != nil {
				f13f0.Enabled = r.ko.Spec.StorageConfig.BlockStorage.Enabled
			}
			f13.BlockStorage = f13f0
		}
		res.StorageConfig = f13
	}
	if r.ko.Spec.Tags != nil {
		res.Tags = aws.ToStringMap(r.ko.Spec.Tags)
	}
	if r.ko.Spec.UpgradePolicy != nil {
		f15 := &svcsdktypes.UpgradePolicyRequest{}
		if r.ko.Spec.UpgradePolicy.SupportType != nil {
			f15.SupportType = svcsdktypes.SupportType(*r.ko.Spec.UpgradePolicy.SupportType)
		}
		res.UpgradePolicy = f15
	}
	if r.ko.Spec.Version != nil {
		res.Version = r.ko.Spec.Version
	}
	if r.ko.Spec.ZonalShiftConfig != nil {
		f17 := &svcsdktypes.ZonalShiftConfigRequest{}
		if r.ko.Spec.ZonalShiftConfig.Enabled != nil {
			f17.Enabled = r.ko.Spec.ZonalShiftConfig.Enabled
		}
		res.ZonalShiftConfig = f17
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return rm.customUpdate(ctx, desired, latest, delta)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	if clusterDeleting(r) {
		return r, requeueWaitWhileDeleting
	}
	inUse, err := rm.clusterInUse(ctx, r)
	if err != nil {
		return nil, err
	} else if inUse {
		return r, requeueWaitWhileInUse
	}
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteClusterOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteCluster(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteCluster", err)
	// After successfully issuing the DeleteCluster API call, the cluster
	// transitions to DELETING state. We must wait until the cluster is fully
	// gone (DescribeCluster returns ResourceNotFoundException) before allowing
	// the finalizer to be removed. This prevents a race condition where the
	// IAM Role CR attempts deletion while EKS-managed instance profiles are
	// still attached to the node role (causing DeleteConflict errors).
	// See: https://github.com/aws-controllers-k8s/iam-controller/pull/181
	if err == nil {
		return r, requeueWaitWhileDeleting
	}

	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteClusterInput, error) {
	res := &svcsdk.DeleteClusterInput{}

	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Cluster,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ResourceLimitExceeded",
		"ResourceNotFound",
		"ResourceInUse",
		"OptInRequired",
		"InvalidParameterCombination",
		"InvalidParameterValue",
		"InvalidQueryParameter",
		"MalformedQueryString",
		"MissingAction",
		"MissingParameter",
		"ValidationError":
		return true
	default:
		return false
	}
}

// newLogging returns a Logging object
// with each the field set by the resource's corresponding spec field.
func (rm *resourceManager) newLogging(
	r *resource,
) *svcsdktypes.Logging {
	res := &svcsdktypes.Logging{}

	if r.ko.Spec.Logging != nil {
		if r.ko.Spec.Logging.ClusterLogging != nil {
			resf0 := []svcsdktypes.LogSetup{}
			for _, resf0iter := range r.ko.Spec.Logging.ClusterLogging {
				resf0elem := &svcsdktypes.LogSetup{}
				if resf0iter.Enabled != nil {
					resf0elem.Enabled = resf0iter.Enabled
				}
				if resf0iter.Types != nil {
					resf0elemf1 := []svcsdktypes.LogType{}
					for _, resf0elemf1iter := range resf0iter.Types {
						var resf0elemf1elem string
						resf0elemf1elem = string(*resf0elemf1iter)
						resf0elemf1 = append(resf0elemf1, svcsdktypes.LogType(resf0elemf1elem))
					}
					resf0elem.Types = resf0elemf1
				}
				resf0 = append(resf0, *resf0elem)
			}
			res.ClusterLogging = resf0
		}

	}

	return res
}

// newVpcConfigRequest returns a VpcConfigRequest object
// with each the field set by the resource's corresponding spec field.
func (rm *resourceManager) newVpcConfigRequest(
	r *resource,
) *svcsdktypes.VpcConfigRequest {
	res := &svcsdktypes.VpcConfigRequest{}

	if r.ko.Spec.ResourcesVPCConfig != nil {
		if r.ko.Spec.ResourcesVPCConfig.EndpointPrivateAccess != nil {
			res.EndpointPrivateAccess = r.ko.Spec.ResourcesVPCConfig.EndpointPrivateAccess
		}
		if r.ko.Spec.ResourcesVPCConfig.EndpointPublicAccess != nil {
			res.EndpointPublicAccess = r.ko.Spec.ResourcesVPCConfig.EndpointPublicAccess
		}
		if r.ko.Spec.ResourcesVPCConfig.PublicAccessCIDRs != nil {
			res.PublicAccessCidrs = aws.ToStringSlice(r.ko.Spec.ResourcesVPCConfig.PublicAccessCIDRs)
		}
		if r.ko.Spec.ResourcesVPCConfig.SecurityGroupIDs != nil {
			res.SecurityGroupIds = aws.ToStringSlice(r.ko.Spec.ResourcesVPCConfig.SecurityGroupIDs)
		}
		if r.ko.Spec.ResourcesVPCConfig.SubnetIDs != nil {
			res.SubnetIds = aws.ToStringSlice(r.ko.Spec.ResourcesVPCConfig.SubnetIDs)
		}

	}

	return res
}
