apiVersion: v1
items:
- apiVersion: eks.services.k8s.aws/v1alpha1
  kind: PodIdentityAssociation
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"eks.services.k8s.aws/v1alpha1","kind":"PodIdentityAssociation","metadata":{"annotations":{},"name":"test-pia-1","namespace":"default"},"spec":{"clusterName":"test-cluster","namespace":"ns","roleARN":"arn:aws:iam::095708837592:role/ack-pipe-role","serviceAccount":"serviceaccount-1","tags":{"v1":"v2"}}}
    creationTimestamp: "2024-02-02T21:55:54Z"
    finalizers:
    - finalizers.eks.services.k8s.aws/PodIdentityAssociation
    generation: 1
    name: test-pia-1
    namespace: default
    resourceVersion: "8256276"
    uid: c441e71c-42bb-4d88-9f98-fc027b4849cd
  spec:
    clusterName: test-cluster
    namespace: ns
    roleARN: arn:aws:iam::095708837592:role/ack-pipe-role
    serviceAccount: serviceaccount-1
    tags:
      v1: v2
  status:
    ackResourceMetadata:
      arn: arn:aws:eks:us-west-2:095708837592:podidentityassociation/test-cluster/a-g1hxih80c1shlxqpx
      ownerAccountID: "095708837592"
      region: us-west-2
    associationARN: arn:aws:eks:us-west-2:095708837592:podidentityassociation/test-cluster/a-g1hxih80c1shlxqpx
    associationID: a-g1hxih80c1shlxqpx
    conditions:
    - lastTransitionTime: "2024-02-02T21:55:56Z"
      message: Resource synced successfully
      reason: ""
      status: "True"
      type: ACK.ResourceSynced
    createdAt: "2024-02-02T21:55:55Z"
    modifiedAt: "2024-02-02T21:55:55Z"
kind: List
metadata:
  resourceVersion: ""
