apiVersion: rbac.authorization.k8s.io/v1
{{ if eq .Values.installScope "cluster" }}
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ack-eks-controller
{{ else }}
kind: Role
metadata:
  creationTimestamp: null
  name: ack-eks-controller
  namespace: {{ .Release.Namespace }}
{{ end }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - eks.services.k8s.aws
  resources:
  - addons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eks.services.k8s.aws
  resources:
  - addons/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - eks.services.k8s.aws
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eks.services.k8s.aws
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - eks.services.k8s.aws
  resources:
  - fargateprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eks.services.k8s.aws
  resources:
  - fargateprofiles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - eks.services.k8s.aws
  resources:
  - nodegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eks.services.k8s.aws
  resources:
  - nodegroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - services.k8s.aws
  resources:
  - fieldexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws
  resources:
  - fieldexports/status
  verbs:
  - get
  - patch
  - update
