---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-eks-reader
  namespace: default
rules:
- apiGroups:
  - eks.services.k8s.aws
  resources:
  - addons
  - clusters
  - fargateprofiles
  - nodegroups
  - podidentityassociations
  verbs:
  - get
  - list
  - watch
