---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-eks-writer
  namespace: default
rules:
- apiGroups:
  - eks.services.k8s.aws
  resources:
  - accessentries
  - addons
  - clusters
  - fargateprofiles
  - identityproviderconfigs
  - nodegroups
  - podidentityassociations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eks.services.k8s.aws
  resources:
  - accessentries
  - addons
  - clusters
  - fargateprofiles
  - identityproviderconfigs
  - nodegroups
  - podidentityassociations
  verbs:
  - get
  - patch
  - update
