// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CapabilitySpec defines the desired state of Capability.
//
// An object representing a managed capability in an Amazon EKS cluster. This
// includes all configuration, status, and health information for the capability.
type CapabilitySpec struct {

	// The name of the Amazon EKS cluster where you want to create the capability.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	ClusterName *string `json:"clusterName"`
	// The configuration settings for the capability. The structure of this object
	// varies depending on the capability type. For Argo CD capabilities, you can
	// configure IAM Identity CenterIAM; Identity Center integration, RBAC role
	// mappings, and network access settings.
	Configuration *CapabilityConfigurationRequest `json:"configuration,omitempty"`
	// Specifies how Kubernetes resources managed by the capability should be handled
	// when the capability is deleted. Currently, the only supported value is RETAIN
	// which retains all Kubernetes resources managed by the capability when the
	// capability is deleted.
	//
	// Because resources are retained, all Kubernetes resources created by the capability
	// should be deleted from the cluster before deleting the capability itself.
	// After the capability is deleted, these resources become difficult to manage
	// because the controller is no longer available.
	// +kubebuilder:validation:Required
	DeletePropagationPolicy *string `json:"deletePropagationPolicy"`
	// A unique name for the capability. The name must be unique within your cluster
	// and can contain alphanumeric characters, hyphens, and underscores.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The Amazon Resource Name (ARN) of the IAM role that the capability uses to
	// interact with Amazon Web Services services. This role must have a trust policy
	// that allows the EKS service principal to assume it, and it must have the
	// necessary permissions for the capability type you're creating.
	//
	// For ACK capabilities, the role needs permissions to manage the resources
	// you want to control through Kubernetes. For Argo CD capabilities, the role
	// needs permissions to access Git repositories and Secrets Manager. For KRO
	// capabilities, the role needs permissions based on the resources you'll be
	// orchestrating.
	// +kubebuilder:validation:Required
	RoleARN *string            `json:"roleARN"`
	Tags    map[string]*string `json:"tags,omitempty"`
	// The type of capability to create. Valid values are:
	//
	//   - ACK – Amazon Web Services Controllers for Kubernetes (ACK), which
	//     lets you manage resources directly from Kubernetes.
	//
	//   - ARGOCD – Argo CD for GitOps-based continuous delivery.
	//
	//   - KRO – Kube Resource Orchestrator (KRO) for composing and managing
	//     custom Kubernetes resources.
	//
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Type *string `json:"type"`
}

// CapabilityStatus defines the observed state of Capability
type CapabilityStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The Unix epoch timestamp in seconds for when the capability was created.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// Health information for the capability, including any issues that may be affecting
	// its operation.
	// +kubebuilder:validation:Optional
	Health *CapabilityHealth `json:"health,omitempty"`
	// The Unix epoch timestamp in seconds for when the capability was last modified.
	// +kubebuilder:validation:Optional
	ModifiedAt *metav1.Time `json:"modifiedAt,omitempty"`
	// The current status of the capability. Valid values include:
	//
	//    * CREATING – The capability is being created.
	//
	//    * ACTIVE – The capability is running and available.
	//
	//    * UPDATING – The capability is being updated.
	//
	//    * DELETING – The capability is being deleted.
	//
	//    * CREATE_FAILED – The capability creation failed.
	//
	//    * UPDATE_FAILED – The capability update failed.
	//
	//    * DELETE_FAILED – The capability deletion failed.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
	// The version of the capability software that is currently running.
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty"`
}

// Capability is the Schema for the Capabilities API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type Capability struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CapabilitySpec   `json:"spec,omitempty"`
	Status            CapabilityStatus `json:"status,omitempty"`
}

// CapabilityList contains a list of Capability
// +kubebuilder:object:root=true
type CapabilityList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Capability `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Capability{}, &CapabilityList{})
}
